# ========== MAIN SETTINGS ==========
SIMILARITY_SCORE = 93
USE_TRANSLATION_SERVICE = False
SPEAK_BACK = False

# ========== VOICE INPUT ==========

# ========== DEFAULT SETTING: MICROPHONE OFF ==========

USE_VOICE_INPUT = False

# ========== DEFAULT SETTING: FALSE, DOES NOT REQUIRE TO PRESS R KEY EVERYTIME ==========

CONTINUOUS_LEARNING = False

# ========== VOICE RECOGNITION ==========


# ========== DEFAULT USAGE: POCKET SPHINX ==========


ENABLE_OFFLINE_RECOGNITION = False

# ========== DEFAULT MICROPHONE TIMEOUT IN SECONDS ==========

DEFAULT_MIC_TIMEOUT = 10

# ========== PREDEFINED COMMANDS USAGE ==========

USE_PREDEFINED_COMMANDS = True


# ========== AN ENDPOINT TO CONNECT WHITE RABBOT AND LOCAL LLM INSTANCES ==========

DEFAULT_LLM_URL = "http://localhost:11434/api/generate"

DEFAULT_DB = "database/db.db"